name: gloss_bloom
description: "Explore \"Gloss Market,\" a stunning Flutter e-commerce app designed for beauty enthusiasts, featuring a comprehensive front-end for gloss sales, vendor management, and an admin panel, all ready for seamless Firebase integration."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.0.0
  flutter_riverpod: ^3.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.0.0
  intl: 0.20.2
  url_launcher: ^6.0.0
  image_picker: '>=1.1.2'
  shared_preferences: ^2.0.0
  cached_network_image: ^3.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.0.0
  freezed: ^3.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
